# Generated by Django 5.2.16 on 2026-08-13 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0003_alter_organization_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeycloakRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full Keycloak role name, e.g. ROLE_DCS_TOSCA_WRITER.', max_length=255, unique=True)),
                ('project', models.CharField(blank=True, default='', help_text='Optional project sub-scope within the org (middle segment); empty for org-level roles like ROLE_DCS_WRITER.', max_length=255)),
                ('level', models.CharField(choices=[('READER', 'Reader'), ('WRITER', 'Writer'), ('ADMIN', 'Admin')], help_text='Access level (trailing role segment).', max_length=16)),
                ('source', models.CharField(choices=[('login', 'Login token'), ('keycloak_admin', 'Keycloak Admin API')], help_text='How this role was first seen.', max_length=32)),
                ('is_active', models.BooleanField(default=True, help_text='Soft-deactivation flag; set False when a role disappears from Keycloak (never hard-deleted -- ACL history may reference it).')),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(help_text='Owning org (first role segment). Mandatory -- a role that resolves to no known Organization is not cataloged.', on_delete=django.db.models.deletion.CASCADE, related_name='keycloak_roles', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Keycloak role',
                'verbose_name_plural': 'Keycloak roles',
                'ordering': ['name'],
            },
        ),
    ]
