# Generated by Django 5.2.16 on 2026-08-13 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_seed_dcs_and_backfill'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeycloakRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Keycloak realm role name, e.g. ROLE_DCS_READER.', max_length=255, unique=True)),
                ('source', models.CharField(choices=[('login', 'Login token'), ('keycloak_admin', 'Keycloak Admin API')], help_text='How this role was first seen.', max_length=32)),
                ('is_active', models.BooleanField(default=True, help_text='Soft-deactivation flag; set False when a role disappears from Keycloak (never hard-deleted -- ACL history may reference it).')),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, help_text="Owning org when the role's slug segment matches a known Organization; null for free roles (e.g. kose-rol-test).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='keycloak_roles', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Keycloak role',
                'verbose_name_plural': 'Keycloak roles',
                'ordering': ['name'],
            },
        ),
    ]
