# Generated by Django 5.1.14 on 2026-04-23 09:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata_providers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geodataengine',
            options={'ordering': ['-is_default', 'name'], 'verbose_name': 'Geodata Provider', 'verbose_name_plural': 'Geodata Providers'},
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='GeoServer style identifier', max_length=100)),
                ('title', models.CharField(blank=True, help_text='Human-readable title', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('format', models.CharField(choices=[('sld', 'SLD'), ('mbstyle', 'MBStyle')], max_length=20)),
                ('file_name', models.CharField(help_text='Original uploaded file name', max_length=255)),
                ('file_content', models.TextField(help_text='Raw SLD XML or MBStyle JSON content')),
                ('content_hash', models.CharField(editable=False, max_length=64)),
                ('validation_state', models.CharField(choices=[('UNKNOWN', 'Unknown'), ('VALID', 'Valid'), ('INVALID', 'Invalid')], default='UNKNOWN', max_length=20)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('remote_state', models.CharField(choices=[('LOCAL_ONLY', 'Local only'), ('SYNCED', 'Synced'), ('FAILED', 'Failed'), ('UNSUPPORTED', 'Unsupported by provider'), ('DELETED', 'Deleted')], default='LOCAL_ONLY', max_length=20)),
                ('remote_error', models.TextField(blank=True)),
                ('remote_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('remote_verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('geodata_engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='styles', to='geodata_providers.geodataengine')),
                ('workspace', models.ForeignKey(blank=True, help_text='Workspace-scoped style. Leave blank for a global engine style.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='styles', to='geodata_providers.workspace')),
            ],
            options={
                'verbose_name': 'Style',
                'verbose_name_plural': 'Styles',
                'ordering': ['geodata_engine__name', 'workspace__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LayerStyleAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('default', 'Default'), ('alternate', 'Alternate')], default='default', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='style_assignments', to='geodata_providers.layer')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layer_assignments', to='geodata_providers.style')),
            ],
            options={
                'db_table': 'geodata_providers_layerstyle',
                'verbose_name': 'Layer Style Assignment',
                'verbose_name_plural': 'Layer Style Assignments',
                'ordering': ['layer__workspace__name', 'layer__name', 'role', 'style__name'],
            },
        ),
        migrations.AddConstraint(
            model_name='style',
            constraint=models.UniqueConstraint(condition=models.Q(('workspace__isnull', False)), fields=('geodata_engine', 'workspace', 'name'), name='unique_style_per_engine_workspace_name'),
        ),
        migrations.AddConstraint(
            model_name='style',
            constraint=models.UniqueConstraint(condition=models.Q(('workspace__isnull', True)), fields=('geodata_engine', 'name'), name='unique_global_style_per_engine_name'),
        ),
        migrations.AddConstraint(
            model_name='layerstyleassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('role', 'default')), fields=('layer',), name='unique_active_default_style_per_layer'),
        ),
        migrations.AddConstraint(
            model_name='layerstyleassignment',
            constraint=models.UniqueConstraint(fields=('layer', 'style', 'role'), name='unique_layer_style_role'),
        ),
    ]
