# Generated by Django 5.1.14 on 2026-04-23 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata_providers', '0002_style_layerstyle'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='opaque',
            field=models.BooleanField(default=False, help_text='GeoServer WMS opaque layer setting.'),
        ),
        migrations.AddField(
            model_name='layer',
            name='queryable',
            field=models.BooleanField(default=True, help_text='GeoServer WMS queryable layer setting.'),
        ),
        migrations.AlterField(
            model_name='style',
            name='file_content',
            field=models.TextField(blank=True, help_text='Raw SLD XML or MBStyle JSON content, when available.'),
        ),
        migrations.AlterField(
            model_name='style',
            name='file_name',
            field=models.CharField(blank=True, help_text='Original uploaded file name, when Django has local style content.', max_length=255),
        ),
    ]
