# Generated by Codex on 2026-05-21

from django.db import migrations, models


def sync_state_field():
    return models.CharField(
        choices=[
            ("UNKNOWN", "Unknown"),
            ("SYNCED", "Synced"),
            ("LOCAL_ONLY", "Local only"),
            ("REMOTE_ONLY", "Remote only"),
            ("STALE", "Stale"),
            ("FAILED", "Failed"),
        ],
        default="LOCAL_ONLY",
        help_text="Current consistency state between Django and the remote provider.",
        max_length=20,
    )


def last_sync_at_field():
    return models.DateTimeField(
        blank=True,
        help_text="Last time this resource was successfully synchronized or checked.",
        null=True,
    )


def last_sync_error_field():
    return models.TextField(
        blank=True,
        help_text="Most recent synchronization error, if any.",
    )


def remote_identifier_field():
    return models.CharField(
        blank=True,
        help_text="Provider-side identifier for diagnostics, when available.",
        max_length=255,
    )


def remote_hash_field():
    return models.CharField(
        blank=True,
        help_text="Provider-side version/hash for diagnostics, when available.",
        max_length=128,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("geodata_providers", "0003_layer_opaque_layer_queryable_and_more"),
    ]

    operations = []
    for model_name in ("layer", "store", "style", "workspace"):
        operations.extend(
            [
                migrations.AddField(
                    model_name=model_name,
                    name="sync_state",
                    field=sync_state_field(),
                ),
                migrations.AddField(
                    model_name=model_name,
                    name="last_sync_at",
                    field=last_sync_at_field(),
                ),
                migrations.AddField(
                    model_name=model_name,
                    name="last_sync_error",
                    field=last_sync_error_field(),
                ),
                migrations.AddField(
                    model_name=model_name,
                    name="remote_identifier",
                    field=remote_identifier_field(),
                ),
                migrations.AddField(
                    model_name=model_name,
                    name="remote_hash",
                    field=remote_hash_field(),
                ),
            ]
        )
