# Generated by Codex on 2026-05-23

from django.db import migrations, models


def backfill_public_url(apps, schema_editor):
    GeodataEngine = apps.get_model("geodata_providers", "GeodataEngine")
    for engine in GeodataEngine.objects.all():
        if not engine.public_url:
            engine.public_url = engine.base_url
            engine.save(update_fields=["public_url"])


class Migration(migrations.Migration):

    dependencies = [
        ("geodata_providers", "0004_sync_state_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="geodataengine",
            name="public_url",
            field=models.CharField(
                blank=True,
                help_text="Externally reachable URL exposed through public catalog bootstrap",
                max_length=255,
            ),
        ),
        migrations.RunPython(backfill_public_url, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="geodataengine",
            name="base_url",
            field=models.CharField(
                help_text="Backend-internal URL used by Django to connect to the engine",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="geodataengine",
            name="public_url",
            field=models.CharField(
                help_text="Externally reachable URL exposed through public catalog bootstrap",
                max_length=255,
            ),
        ),
    ]
