# Generated by Django 5.2.16 on 2026-07-10 08:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata_providers', '0006_alter_geodataengine_id_alter_layer_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='geodataengine',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Is this engine instance active?'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='sync_state',
            field=models.CharField(choices=[('UNKNOWN', 'Unknown'), ('SYNCED', 'Synced'), ('LOCAL_ONLY', 'Local only'), ('REMOTE_ONLY', 'Remote only'), ('STALE', 'Stale'), ('FAILED', 'Failed')], db_index=True, default='LOCAL_ONLY', help_text='Current consistency state between Django and the remote provider.', max_length=20),
        ),
        migrations.AlterField(
            model_name='store',
            name='sync_state',
            field=models.CharField(choices=[('UNKNOWN', 'Unknown'), ('SYNCED', 'Synced'), ('LOCAL_ONLY', 'Local only'), ('REMOTE_ONLY', 'Remote only'), ('STALE', 'Stale'), ('FAILED', 'Failed')], db_index=True, default='LOCAL_ONLY', help_text='Current consistency state between Django and the remote provider.', max_length=20),
        ),
        migrations.AlterField(
            model_name='style',
            name='sync_state',
            field=models.CharField(choices=[('UNKNOWN', 'Unknown'), ('SYNCED', 'Synced'), ('LOCAL_ONLY', 'Local only'), ('REMOTE_ONLY', 'Remote only'), ('STALE', 'Stale'), ('FAILED', 'Failed')], db_index=True, default='LOCAL_ONLY', help_text='Current consistency state between Django and the remote provider.', max_length=20),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='sync_state',
            field=models.CharField(choices=[('UNKNOWN', 'Unknown'), ('SYNCED', 'Synced'), ('LOCAL_ONLY', 'Local only'), ('REMOTE_ONLY', 'Remote only'), ('STALE', 'Stale'), ('FAILED', 'Failed')], db_index=True, default='LOCAL_ONLY', help_text='Current consistency state between Django and the remote provider.', max_length=20),
        ),
        migrations.AddIndex(
            model_name='layer',
            index=models.Index(fields=['workspace', 'is_public', 'publishing_state'], name='geoprov_layer_ws_pub_state_idx'),
        ),
    ]
