# Generated by Django 5.2.16 on 2026-07-13 07:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata_providers', '0007_alter_geodataengine_is_active_alter_layer_sync_state_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='layer',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='store',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='workspace',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='layer',
            constraint=models.UniqueConstraint(fields=('workspace', 'name'), name='unique_layer_name_per_workspace'),
        ),
        migrations.AddConstraint(
            model_name='store',
            constraint=models.UniqueConstraint(fields=('workspace', 'name'), name='unique_store_name_per_workspace'),
        ),
        migrations.AddConstraint(
            model_name='workspace',
            constraint=models.UniqueConstraint(fields=('geodata_engine', 'name'), name='unique_workspace_name_per_engine'),
        ),
    ]
