# Generated by Django 5.2.16 on 2026-08-09 22:27

import django.db.models.deletion
import tosca_api.apps.geodata_providers.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata_providers', '0008_alter_layer_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LayerGroup',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sync_state', models.CharField(choices=[('UNKNOWN', 'Unknown'), ('SYNCED', 'Synced'), ('LOCAL_ONLY', 'Local only'), ('REMOTE_ONLY', 'Remote only'), ('STALE', 'Stale'), ('FAILED', 'Failed')], db_index=True, default='LOCAL_ONLY', help_text='Current consistency state between Django and the remote provider.', max_length=20)),
                ('last_sync_at', models.DateTimeField(blank=True, help_text='Last time this resource was successfully synchronized or checked.', null=True)),
                ('last_sync_error', models.TextField(blank=True, help_text='Most recent synchronization error, if any.')),
                ('remote_identifier', models.CharField(blank=True, help_text='Provider-side identifier for diagnostics, when available.', max_length=255)),
                ('remote_hash', models.CharField(blank=True, help_text='Provider-side version/hash for diagnostics, when available.', max_length=128)),
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('render_type', models.CharField(choices=[('VECTOR', 'Vector'), ('RASTER', 'Raster')], max_length=10)),
                ('publishing_state', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('FAILED', 'Failed'), ('UNPUBLISHED', 'Unpublished')], default='DRAFT', max_length=20)),
                ('is_public', models.BooleanField(default=False)),
                ('publishing_error', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('default_style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='layer_groups', to='geodata_providers.style')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layer_groups', to='geodata_providers.workspace')),
            ],
            options={
                'ordering': ['workspace__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LayerGroupMember',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('source_alias', models.CharField(blank=True, help_text='Source name referenced by MBStyle layers; defaults to the layer name.', max_length=100)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='geodata_providers.layergroup')),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_memberships', to='geodata_providers.layer')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SpriteAsset',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=tosca_api.apps.geodata_providers.models.sprite_image_upload_to)),
                ('index_content', models.JSONField(default=dict)),
                ('content_hash', models.CharField(blank=True, editable=False, max_length=64)),
                ('validation_state', models.CharField(choices=[('UNKNOWN', 'Unknown'), ('VALID', 'Valid'), ('INVALID', 'Invalid')], default='UNKNOWN', max_length=20)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('geodata_engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprite_assets', to='geodata_providers.geodataengine')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sprite_assets', to='geodata_providers.workspace')),
            ],
            options={
                'ordering': ['geodata_engine__name', 'workspace__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='style',
            name='sprite_asset',
            field=models.ForeignKey(blank=True, help_text='Optional MapLibre sprite sheet used by this MBStyle.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='styles', to='geodata_providers.spriteasset'),
        ),
        migrations.AddIndex(
            model_name='layergroup',
            index=models.Index(fields=['workspace', 'is_public', 'publishing_state'], name='geoprov_group_ws_pub_state_idx'),
        ),
        migrations.AddConstraint(
            model_name='layergroup',
            constraint=models.UniqueConstraint(fields=('workspace', 'name'), name='unique_layer_group_name_per_workspace'),
        ),
        migrations.AddConstraint(
            model_name='layergroupmember',
            constraint=models.UniqueConstraint(fields=('group', 'layer'), name='unique_layer_per_group'),
        ),
        migrations.AddConstraint(
            model_name='layergroupmember',
            constraint=models.UniqueConstraint(fields=('group', 'order'), name='unique_order_per_group'),
        ),
        migrations.AddConstraint(
            model_name='layergroupmember',
            constraint=models.UniqueConstraint(fields=('group', 'source_alias'), name='unique_source_alias_per_group'),
        ),
        migrations.AddConstraint(
            model_name='spriteasset',
            constraint=models.UniqueConstraint(condition=models.Q(('workspace__isnull', False)), fields=('geodata_engine', 'workspace', 'name'), name='unique_sprite_per_engine_workspace_name'),
        ),
        migrations.AddConstraint(
            model_name='spriteasset',
            constraint=models.UniqueConstraint(condition=models.Q(('workspace__isnull', True)), fields=('geodata_engine', 'name'), name='unique_global_sprite_per_engine_name'),
        ),
    ]
