# Generated by Django 5.2.16 on 2026-08-12 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata_providers', '0008_alter_layer_unique_together_and_more'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Owning organization; derives GeoServer ACL roles from its slug.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workspaces', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public')], db_index=True, default='private', help_text='PRIVATE: owner org only. PUBLIC: anonymous read + owner-org write.', max_length=20),
        ),
    ]
