# Generated by Django 5.2.16 on 2026-08-10 11:30

import django.db.models.deletion
import json
from django.db import migrations, models


def pin_existing_group_styles(apps, schema_editor):
    LayerGroupMember = apps.get_model('geodata_providers', 'LayerGroupMember')
    LayerStyleAssignment = apps.get_model('geodata_providers', 'LayerStyleAssignment')

    for member in LayerGroupMember.objects.select_related(
        'group__default_style',
        'layer',
    ).iterator():
        style = member.group.default_style
        if style is None:
            continue
        assignment = (
            LayerStyleAssignment.objects.filter(layer_id=member.layer_id, style_id=style.id)
            .order_by('-is_active', 'role', 'created_at')
            .first()
        )
        if assignment is None:
            has_default = LayerStyleAssignment.objects.filter(
                layer_id=member.layer_id,
                role='default',
                is_active=True,
            ).exists()
            assignment = LayerStyleAssignment.objects.create(
                layer_id=member.layer_id,
                style_id=style.id,
                role='alternate' if has_default else 'default',
                is_active=True,
                created_by_id=member.group.created_by_id,
            )
        elif not assignment.is_active:
            assignment.is_active = True
            assignment.save(update_fields=['is_active', 'updated_at'])

        if style.format == 'mbstyle':
            try:
                payload = json.loads(style.file_content)
            except (TypeError, json.JSONDecodeError):
                payload = {}
            selected_ids = [
                layer.get('id')
                for layer in payload.get('layers', [])
                if isinstance(layer, dict)
                and isinstance(layer.get('id'), str)
                and layer.get('source') == member.source_alias
            ]
            if selected_ids:
                merged_ids = list(dict.fromkeys([*assignment.style_layer_ids, *selected_ids]))
                assignment.style_layer_ids = merged_ids
                assignment.save(update_fields=['style_layer_ids', 'updated_at'])

        member.style_assignment_id = assignment.id
        member.save(update_fields=['style_assignment', 'updated_at'])


def restore_group_style_fields(apps, schema_editor):
    LayerGroup = apps.get_model('geodata_providers', 'LayerGroup')
    for group in LayerGroup.objects.prefetch_related(
        'members__layer__store',
        'members__style_assignment',
    ).iterator():
        members = list(group.members.all())
        if not members:
            continue
        first = members[0]
        group.default_style_id = (
            None if first.style_assignment_id is None else first.style_assignment.style_id
        )
        group.render_type = (
            'RASTER' if first.layer.store.store_type == 'geotiff' else 'VECTOR'
        )
        group.save(update_fields=['default_style', 'render_type', 'updated_at'])


class Migration(migrations.Migration):

    dependencies = [
        ('geodata_providers', '0009_layergroup_layergroupmember_spriteasset_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='layergroupmember',
            name='unique_layer_per_group',
        ),
        migrations.AddField(
            model_name='layerstyleassignment',
            name='style_layer_ids',
            field=models.JSONField(blank=True, default=list, help_text='Ordered MBStyle layer IDs that apply to this data layer. Leave empty for SLD assignments.'),
        ),
        migrations.AddField(
            model_name='layergroupmember',
            name='style_assignment',
            field=models.ForeignKey(blank=True, help_text="Pinned style assignment; defaults to the layer's active default assignment.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group_memberships', to='geodata_providers.layerstyleassignment'),
        ),
        migrations.RunPython(pin_existing_group_styles, restore_group_style_fields),
        migrations.RemoveField(
            model_name='layergroup',
            name='default_style',
        ),
        migrations.RemoveField(
            model_name='layergroup',
            name='render_type',
        ),
    ]
