# Generated by Django 5.2.16 on 2026-08-10

import tosca_api.apps.geodata_providers.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geodata_providers", "0010_remove_layergroupmember_unique_layer_per_group_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="layergroup",
            name="legend_composition_hash",
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name="layergroup",
            name="legend_content_hash",
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name="layergroup",
            name="legend_image",
            field=models.ImageField(
                blank=True,
                help_text=(
                    "Optional curated legend for the complete group. PNG, JPEG, and WebP "
                    "are supported; when present it replaces generated member legends."
                ),
                upload_to=tosca_api.apps.geodata_providers.models.layer_group_legend_upload_to,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["png", "jpg", "jpeg", "webp"]
                    )
                ],
            ),
        ),
    ]
