# Generated by Django 5.2.16 on 2026-08-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata_providers', '0011_layergroup_legend'),
    ]

    operations = [
        migrations.AddField(
            model_name='layergroupmember',
            name='render_layer_ids',
            field=models.JSONField(
                blank=True,
                default=list,
                help_text=(
                    "Optional MBStyle layer IDs for this group member. "
                    "Leave empty to use the pinned assignment's selected layer IDs."
                ),
            ),
        ),
        migrations.AddField(
            model_name='layergroupmember',
            name='title',
            field=models.CharField(
                blank=True,
                help_text='Optional label for this render pass; defaults to the layer title.',
                max_length=200,
            ),
        ),
    ]
