# Generated by Django 5.2.16 on 2026-08-14 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geodata_providers', '0010_workspace_organization_nonnull'),
        ('geodata_providers', '0015_spriteasset_high_dpi'),
    ]

    operations = [
    ]
