# Generated by Django 5.2.16 on 2026-08-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata_providers', '0016_merge_20260814_0525'),
        ('organizations', '0007_userauthorizationsnapshot_platform_exempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='geodataengine',
            name='organizations',
            field=models.ManyToManyField(blank=True, help_text='Restrict this engine to specific organizations. Leave empty to allow every organization entitled to Geodata Providers.', related_name='geodata_engines', to='organizations.organization'),
        ),
    ]
