# Generated by Django 5.2.16 on 2026-10-07 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata_providers', '0017_geodataengine_organizations'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='attributes',
            field=models.JSONField(blank=True, default=list, help_text='Non-geometry feature attributes reported by the engine, as [{"name": ..., "type": ...}]. Empty for raster layers.'),
        ),
    ]
