# Generated by Django 5.2.16 on 2026-10-07 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata_providers', '0018_layer_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='bounds',
            field=models.JSONField(blank=True, help_text='WGS84 extent reported by the engine, as [west, south, east, north].', null=True),
        ),
    ]
