# Generated by Django 5.1.14 on 2026-03-19 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventseries_eventtype_event_access_notes_and_more'),
        ('geocontext', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventseries',
            name='default_context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_event_series', to='geocontext.geocontext'),
        ),
        migrations.AlterField(
            model_name='event',
            name='context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='geocontext.geocontext'),
        ),
    ]
