# Generated by Django 5.1.14 on 2026-03-19 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
        ('events', '0003_eventseries_default_context_alter_event_context'),
        ('geocontext', '0001_initial'),
        ('layerrefs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventseries',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_series', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='eventseries',
            name='event_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='series', to='events.eventtype'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['campaign', 'status', 'start_datetime'], name='events_evt_cmp_stat_start_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_type', 'start_datetime'], name='events_evt_type_start_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['location_mode', 'start_datetime'], name='events_evt_locmode_start_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['series', 'start_datetime'], name='events_evt_series_start_idx'),
        ),
        migrations.AddIndex(
            model_name='eventseries',
            index=models.Index(fields=['campaign', 'event_type'], name='events_even_campaig_ba0154_idx'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(condition=models.Q(('series__isnull', False)), fields=('series', 'occurrence_index'), name='events_evt_ser_occ_uniq'),
        ),
    ]
