# Generated by Django 5.1.14 on 2026-03-19 09:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_eventseries_campaign_eventseries_event_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxonomyDimension',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('selection_mode', models.CharField(choices=[('single', 'Single'), ('multiple', 'Multiple')], default='multiple', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Taxonomy Dimension',
                'verbose_name_plural': 'Taxonomy Dimensions',
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='TaxonomyTerm',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='events.taxonomydimension')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='events.taxonomyterm')),
            ],
            options={
                'verbose_name': 'Taxonomy Term',
                'verbose_name_plural': 'Taxonomy Terms',
                'ordering': ['dimension_id', 'sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='EventTerm',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_terms', to='events.event')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_terms', to='events.taxonomyterm')),
            ],
            options={
                'verbose_name': 'Event Term',
                'verbose_name_plural': 'Event Terms',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='taxonomyterm',
            constraint=models.UniqueConstraint(fields=('dimension', 'code'), name='events_tax_term_dim_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='eventterm',
            constraint=models.UniqueConstraint(fields=('event', 'term'), name='events_event_term_uniq'),
        ),
    ]
