# Generated by Django 5.1.14 on 2026-03-19 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_taxonomydimension_taxonomyterm_eventterm_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='eventterm',
            index=models.Index(fields=['term', 'event'], name='events_evtterm_term_evt_idx'),
        ),
    ]
