# Generated by Django 5.1.14 on 2026-03-19 11:43

from django.db import migrations, models


def seed_event_types(apps, schema_editor):
    EventType = apps.get_model("events", "EventType")

    seed_rows = [
        {
            "code": "general",
            "label": "General",
            "profile_mode": "core",
            "profile_key": None,
            "is_active": True,
        },
        {
            "code": "public_health",
            "label": "Public Health",
            "profile_mode": "extension",
            "profile_key": "public_health",
            "is_active": True,
        },
        {
            "code": "sports",
            "label": "Sports",
            "profile_mode": "extension",
            "profile_key": "sports",
            "is_active": True,
        },
        {
            "code": "culture",
            "label": "Culture",
            "profile_mode": "extension",
            "profile_key": "culture",
            "is_active": True,
        },
    ]

    for row in seed_rows:
        EventType.objects.update_or_create(code=row["code"], defaults=row)


def unseed_event_types(apps, schema_editor):
    EventType = apps.get_model("events", "EventType")
    EventType.objects.filter(
        code__in=["general", "public_health", "sports", "culture"]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_eventterm_events_evtterm_term_evt_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='profile_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='profile_mode',
            field=models.CharField(choices=[('core', 'Core'), ('extension', 'Extension')], default='core', max_length=20),
        ),
        migrations.RunPython(seed_event_types, unseed_event_types),
    ]
