# Generated by Django 5.1.14 on 2026-03-19 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_eventtype_is_active_eventtype_profile_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CultureEventProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='culture_profile', serialize=False, to='events.event')),
                ('format_label', models.CharField(blank=True, default='', max_length=255)),
                ('age_rating', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'verbose_name': 'Culture Event Profile',
                'verbose_name_plural': 'Culture Event Profiles',
            },
        ),
        migrations.CreateModel(
            name='PublicHealthEventProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='public_health_profile', serialize=False, to='events.event')),
                ('insurance_eligible', models.BooleanField(default=False)),
                ('referral_required', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Public Health Event Profile',
                'verbose_name_plural': 'Public Health Event Profiles',
            },
        ),
        migrations.CreateModel(
            name='SportsEventProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='sports_profile', serialize=False, to='events.event')),
                ('sport_name', models.CharField(blank=True, default='', max_length=255)),
                ('skill_level', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'verbose_name': 'Sports Event Profile',
                'verbose_name_plural': 'Sports Event Profiles',
            },
        ),
    ]
