# Generated by Django 5.1.14 on 2026-03-19 13:28

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_cultureeventprofile_publichealtheventprofile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventseries',
            name='by_weekday',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='eventseries',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_event_series', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventseries',
            name='day_of_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventseries',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventseries',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventseries',
            name='interval',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='eventseries',
            name='monthly_rule_type',
            field=models.CharField(blank=True, choices=[('day_of_month', 'Day of Month'), ('nth_weekday', 'Nth Weekday')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='eventseries',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='eventseries',
            name='occurrence_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventseries',
            name='recurrence_type',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='eventseries',
            name='series_mode',
            field=models.CharField(choices=[('manual_batch', 'Manual Batch'), ('recurring', 'Recurring')], default='manual_batch', max_length=20),
        ),
        migrations.AddField(
            model_name='eventseries',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventseries',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventseries',
            name='timezone',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='eventseries',
            name='week_of_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventseries',
            name='weekday_of_month',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.CreateModel(
            name='EventSeriesDate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('occurrence_date', models.DateField()),
                ('display_order', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='events.eventseries')),
            ],
            options={
                'verbose_name': 'Event Series Date',
                'verbose_name_plural': 'Event Series Dates',
                'ordering': ['display_order', 'occurrence_date', 'created_at'],
                'constraints': [models.UniqueConstraint(fields=('series', 'occurrence_date'), name='events_evtseriesdate_series_date_uniq')],
            },
        ),
    ]
