# Generated by Django 5.1.14 on 2026-03-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_eventseries_by_weekday_eventseries_created_by_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventlayer',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='eventlayer',
            constraint=models.UniqueConstraint(fields=('event', 'layer'), name='events_event_layer_uniq'),
        ),
    ]
