# Generated by Codex on 2026-03-19

from itertools import groupby
from operator import attrgetter

from django.db import migrations


def backfill_taxonomy_sort_orders(apps, schema_editor):
    TaxonomyDimension = apps.get_model("events", "TaxonomyDimension")
    TaxonomyTerm = apps.get_model("events", "TaxonomyTerm")

    max_dimension_order = (
        TaxonomyDimension.objects.exclude(sort_order=0).order_by("-sort_order").values_list(
            "sort_order",
            flat=True,
        ).first()
        or 0
    )
    next_dimension_order = max_dimension_order + 1
    for dimension in TaxonomyDimension.objects.filter(sort_order=0).order_by(
        "created_at",
        "id",
    ):
        dimension.sort_order = next_dimension_order
        dimension.save(update_fields=["sort_order"])
        next_dimension_order += 1

    terms = list(
        TaxonomyTerm.objects.all().order_by(
            "dimension_id",
            "parent_id",
            "created_at",
            "id",
        )
    )
    for _, scoped_terms_iter in groupby(terms, key=attrgetter("dimension_id", "parent_id")):
        scoped_terms = list(scoped_terms_iter)
        existing_orders = [term.sort_order for term in scoped_terms if term.sort_order > 0]
        next_term_order = (max(existing_orders) if existing_orders else 0) + 1

        for term in scoped_terms:
            if term.sort_order > 0:
                continue
            term.sort_order = next_term_order
            term.save(update_fields=["sort_order"])
            next_term_order += 1


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0010_alter_eventlayer_unique_together_and_more"),
    ]

    operations = [
        migrations.RunPython(
            backfill_taxonomy_sort_orders,
            migrations.RunPython.noop,
        ),
    ]
