# Generated by Django 5.1.14 on 2026-03-19 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_backfill_taxonomy_sort_orders'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxonomyterm',
            options={'ordering': ['dimension_id', 'parent_id', 'sort_order', 'label'], 'verbose_name': 'Taxonomy Term', 'verbose_name_plural': 'Taxonomy Terms'},
        ),
    ]
