# Generated by Django 5.1.15 on 2026-05-25 22:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_alter_event_layers_alter_eventlayer_layer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.RemoveField(
            model_name='event',
            name='provider_contact',
        ),
        migrations.AddField(
            model_name='event',
            name='district',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='event',
            name='external_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='event',
            name='language',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('de', 'Deutsch'), ('en', 'English'), ('tr', 'Türkçe'), ('ar', 'العربية'), ('ru', 'Русский'), ('fr', 'Français'), ('es', 'Español'), ('uk', 'Українська'), ('fa', 'فارسی'), ('pl', 'Polski'), ('other', 'Other')], max_length=8), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='event',
            name='language_note',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='lead_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='event',
            name='provider_address',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='event',
            name='provider_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='event',
            name='provider_phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='provider_social',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='event',
            name='summary',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='venue_address',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
