# Generated by Django 5.1.15 on 2026-05-25 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_remove_event_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location_mode',
            field=models.CharField(choices=[('physical', 'Physical'), ('online', 'Online'), ('hybrid', 'Hybrid'), ('by_arrangement', 'By Arrangement'), ('home_visit', 'Home Visit')], default='physical', max_length=20),
        ),
    ]
