# Generated by Django 5.1.15 on 2026-05-25 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_alter_event_location_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxonomydimension',
            name='profile_key',
            field=models.CharField(blank=True, default='', help_text='Restrict this dimension to events whose event_type.profile_key matches. Empty = available to every event.', max_length=100),
        ),
    ]
