# Generated by Django 5.1.15 on 2026-05-26 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_taxonomydimension_profile_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='publichealtheventprofile',
            name='cost_amount_eur',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='publichealtheventprofile',
            name='reduced_amount_eur',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='publichealtheventprofile',
            name='registration',
            field=models.CharField(blank=True, choices=[('required', 'Required'), ('not_required', 'Not Required'), ('by_arrangement', 'By Arrangement')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='publichealtheventprofile',
            name='short_notice_possible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publichealtheventprofile',
            name='subsidy_program',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='publichealtheventprofile',
            name='target_age_note',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='publichealtheventprofile',
            name='transit_note',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
