# Generated by Django 5.2.16 on 2026-07-10 08:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_alter_campaign_id'),
        ('events', '0019_alter_event_id_alter_eventlayer_id_and_more'),
        ('geocontext', '0004_alter_geocontext_id'),
        ('geodata_providers', '0007_alter_geodataengine_is_active_alter_layer_sync_state_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status', 'visibility', 'start_datetime'], name='events_evt_stat_vis_start_idx'),
        ),
    ]
