# Generated by Django 5.2.16 on 2026-07-13 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_alter_campaign_id'),
        ('events', '0020_alter_event_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlayer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='eventseries',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_series', to='campaigns.campaign'),
        ),
    ]
