# Generated by Django 5.2.16 on 2026-08-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_eventlayer_updated_at_alter_eventseries_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', help_text='Deprecated (epic-11 §3.2): not used for authorization. Read-only via the API -- see effective_visibility.', max_length=20),
        ),
    ]
