# Generated by Django 5.1.14 on 2026-03-04 19:37

import django.db.models.deletion
import tosca_api.apps.geodata_engine.encryption
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeodataEngine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Engine name (e.g., 'Default GeoServer', 'Production Martin')", max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of this geodata engine instance')),
                ('engine_type', models.CharField(choices=[('geoserver', 'GeoServer'), ('martin', 'Martin Tiles'), ('pg_tileserv', 'PostGIS TileServer')], default='geoserver', help_text='Type of geodata engine', max_length=50)),
                ('base_url', models.CharField(help_text='Full URL to the engine', max_length=255)),
                ('admin_username', models.CharField(blank=True, default='admin2', help_text='Admin username (if applicable)', max_length=100)),
                ('admin_password', models.CharField(blank=True, default='geoserver2', help_text='Admin password (if applicable)', max_length=100)),
                ('api_key', models.CharField(blank=True, help_text='API key for engines that require it', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Is this engine instance active?')),
                ('is_default', models.BooleanField(default=False, help_text='Is this the default engine instance?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Geodata Engine Instance',
                'verbose_name_plural': 'Geodata Engine Instances',
                'ordering': ['-is_default', 'name'],
            },
            bases=(models.Model, tosca_api.apps.geodata_engine.encryption.EncryptedCharField),
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Workspace name (e.g., 'mobility', 'environment')", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of this workspace')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('geodata_engine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workspaces', to='geodata_engine.geodataengine')),
            ],
            options={
                'verbose_name': 'Workspace',
                'verbose_name_plural': 'Workspaces',
                'ordering': ['name'],
                'unique_together': {('geodata_engine', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Store name for identification', max_length=100)),
                ('store_type', models.CharField(choices=[('postgis', 'PostGIS Database'), ('file', 'File-based Store (Shapefile, GeoPackage, GeoJSON, Directory)'), ('geotiff', 'GeoTIFF')], default='postgis', help_text='Type of data store', max_length=20)),
                ('host', models.CharField(blank=True, help_text='PostGIS host (for PostGIS stores)', max_length=255)),
                ('port', models.IntegerField(blank=True, default=5432, help_text='PostGIS port (for PostGIS stores)', null=True)),
                ('database', models.CharField(blank=True, help_text='PostGIS database name (for PostGIS stores)', max_length=100)),
                ('username', models.CharField(blank=True, help_text='PostGIS username (for PostGIS stores)', max_length=100)),
                ('password', models.CharField(blank=True, help_text='PostGIS password (for PostGIS stores)', max_length=100)),
                ('schema', models.CharField(blank=True, default='public', help_text='PostGIS schema (for PostGIS stores)', max_length=100)),
                ('file_path', models.CharField(blank=True, help_text='File or directory path', max_length=500)),
                ('charset', models.CharField(blank=True, default='UTF-8', help_text='Character encoding', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('geodata_engine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='geodata_engine.geodataengine')),
                ('workspace', models.ForeignKey(blank=True, help_text='Workspace this store belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='geodata_engine.workspace')),
            ],
            options={
                'verbose_name': 'Data Store',
                'verbose_name_plural': 'Data Stores',
                'ordering': ['store_type', 'name'],
                'unique_together': {('workspace', 'name')},
            },
            bases=(models.Model, tosca_api.apps.geodata_engine.encryption.EncryptedCharField),
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Layer name', max_length=100)),
                ('title', models.CharField(blank=True, help_text='Human-readable title', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('table_name', models.CharField(help_text='PostGIS table name', max_length=100)),
                ('geometry_column', models.CharField(default='geom', help_text='Geometry column name', max_length=100)),
                ('geometry_type', models.CharField(choices=[('Point', 'Point'), ('LineString', 'LineString'), ('Polygon', 'Polygon'), ('MultiPoint', 'MultiPoint'), ('MultiLineString', 'MultiLineString'), ('MultiPolygon', 'MultiPolygon'), ('GeometryCollection', 'GeometryCollection')], help_text='Geometry type', max_length=50)),
                ('srid', models.IntegerField(default=4326, help_text='Spatial Reference System Identifier')),
                ('publishing_state', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('FAILED', 'Failed'), ('UNPUBLISHED', 'Unpublished')], default='DRAFT', help_text='Current publishing state', max_length=20)),
                ('is_public', models.BooleanField(default=False, help_text='If true, layer can be listed and retrieved without authentication.')),
                ('published_url', models.URLField(blank=True, help_text='Published layer URL (WFS/WMS)')),
                ('publishing_error', models.TextField(blank=True, help_text='Last publishing error message')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='geodata_engine.store')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='geodata_engine.workspace')),
            ],
            options={
                'verbose_name': 'Layer',
                'verbose_name_plural': 'Layers',
                'ordering': ['workspace__name', 'name'],
                'unique_together': {('workspace', 'name')},
            },
        ),
    ]
