# Generated by Django 5.1.14 on 2026-02-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='geodataengine',
            name='api_key',
            field=models.CharField(blank=True, help_text='API key for engines that require it', max_length=255),
        ),
        migrations.AddField(
            model_name='geodataengine',
            name='engine_type',
            field=models.CharField(choices=[('geoserver', 'GeoServer'), ('martin', 'Martin Tiles'), ('pg_tileserv', 'PostGIS TileServer'), ('mapproxy', 'MapProxy')], default='geoserver', help_text='Type of geodata engine', max_length=50),
        ),
        migrations.AlterField(
            model_name='geodataengine',
            name='admin_password',
            field=models.CharField(blank=True, default='geoserver2', help_text='Admin password (if applicable)', max_length=100),
        ),
        migrations.AlterField(
            model_name='geodataengine',
            name='admin_username',
            field=models.CharField(blank=True, default='admin2', help_text='Admin username (if applicable)', max_length=100),
        ),
        migrations.AlterField(
            model_name='geodataengine',
            name='base_url',
            field=models.CharField(help_text="Full URL to the engine (e.g., 'http://geoserver:8080/geoserver')", max_length=255),
        ),
        migrations.AlterField(
            model_name='geodataengine',
            name='description',
            field=models.TextField(blank=True, help_text='Description of this geodata engine instance'),
        ),
        migrations.AlterField(
            model_name='geodataengine',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is this engine instance active?'),
        ),
        migrations.AlterField(
            model_name='geodataengine',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Is this the default engine instance?'),
        ),
        migrations.AlterField(
            model_name='geodataengine',
            name='name',
            field=models.CharField(help_text="Engine name (e.g., 'Default GeoServer', 'Production Martin')", max_length=100, unique=True),
        ),
    ]
