"""
Custom deploy-time system checks (issue 19: settings hardening).

These run automatically under `manage.py check --deploy`, on top of
Django's own built-in deploy checks (which already cover DEBUG=True and an
empty/wildcard ALLOWED_HOSTS). Registered from CoreConfig.ready().
"""
from cryptography.fernet import Fernet
from django.conf import settings
from django.core.checks import Error, Tags, register

DEFAULT_SECRET_KEY = "change-me-in-production"
DEFAULT_GEOSERVER_ADMIN_PASSWORD = "geoserver2"
DEFAULT_KEYCLOAK_CLIENT_ID = "django-dev"


@register(Tags.security, deploy=True)
def check_secret_key(app_configs, **kwargs):
    if not settings.SECRET_KEY or settings.SECRET_KEY == DEFAULT_SECRET_KEY:
        return [
            Error(
                "SECRET_KEY is unset or still the insecure development default.",
                hint="Set DJANGO_SECRET_KEY to a unique, unpredictable value.",
                id="tosca.settings.E001",
            )
        ]
    return []


@register(Tags.security, deploy=True)
def check_field_encryption_key(app_configs, **kwargs):
    key = getattr(settings, "FIELD_ENCRYPTION_KEY", "")
    if not key:
        return [
            Error(
                "FIELD_ENCRYPTION_KEY is not set.",
                hint="Generate one with: python -c \"from cryptography.fernet import "
                     "Fernet; print(Fernet.generate_key().decode())\"",
                id="tosca.settings.E002",
            )
        ]
    try:
        Fernet(key.encode() if isinstance(key, str) else key)
    except (ValueError, TypeError):
        return [
            Error(
                "FIELD_ENCRYPTION_KEY is not a valid Fernet key.",
                hint="It must be a 32-byte urlsafe-base64-encoded key generated by Fernet.generate_key().",
                id="tosca.settings.E003",
            )
        ]
    return []


@register(Tags.security, deploy=True)
def check_keycloak_settings(app_configs, **kwargs):
    errors = []
    if not settings.KEYCLOAK_ISSUER:
        errors.append(
            Error("KEYCLOAK_ISSUER is not set.", id="tosca.settings.E004")
        )
    if not settings.KEYCLOAK_JWKS_URL:
        errors.append(
            Error("KEYCLOAK_JWKS_URL is not set.", id="tosca.settings.E005")
        )
    if not settings.KEYCLOAK_CLIENT_ID or settings.KEYCLOAK_CLIENT_ID == DEFAULT_KEYCLOAK_CLIENT_ID:
        errors.append(
            Error(
                "KEYCLOAK_CLIENT_ID is unset or still the local-dev default ('django-dev').",
                hint="Set KEYCLOAK_CLIENT_ID to this deployment's real Keycloak client id.",
                id="tosca.settings.E006",
            )
        )
    return errors


@register(Tags.security, deploy=True)
def check_geoserver_admin_password(app_configs, **kwargs):
    if settings.GEOSERVER_ADMIN_PASSWORD == DEFAULT_GEOSERVER_ADMIN_PASSWORD:
        return [
            Error(
                "GEOSERVER_ADMIN_PASSWORD is still the insecure default ('geoserver2').",
                hint="Set GEOSERVER_ADMIN_PASSWORD to this deployment's real GeoServer admin password.",
                id="tosca.settings.E007",
            )
        ]
    return []


@register(Tags.security, deploy=True)
def check_static_and_media_roots(app_configs, **kwargs):
    errors = []
    if getattr(settings, "STATIC_ROOT", None) is None:
        errors.append(
            Error("STATIC_ROOT is not configured.", id="tosca.settings.E008")
        )
    if getattr(settings, "MEDIA_ROOT", None) is None:
        errors.append(
            Error("MEDIA_ROOT is not configured.", id="tosca.settings.E009")
        )
    return errors
