# Generated by Django 5.1.14 on 2026-02-04 12:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoContext',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, default='')),
                ('content_type', models.CharField(choices=[('simple', 'Simple Text'), ('rich', 'Rich HTML')], default='simple', max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='geocontexts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'GeoContext',
                'verbose_name_plural': 'GeoContexts',
                'ordering': ['-created_at'],
            },
        ),
    ]
