# Generated by Django 5.2.16 on 2026-10-07 07:22

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0008_alter_userauthorizationsnapshot_platform_exempt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower values are listed first.')),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private (signed-in users only)')], db_index=True, default='PRIVATE', help_text='PUBLIC: listed to everyone. PRIVATE: not listed to anonymous users, listed to signed-in users. This controls what TOSCA lists; the remote data itself stays publicly reachable.', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='Owning organization; scopes who may manage this category.', on_delete=django.db.models.deletion.PROTECT, related_name='external_categories', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'External Category',
                'verbose_name_plural': 'External Categories',
                'ordering': ['display_order', 'title', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExternalService',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Admin label', max_length=100)),
                ('slug', models.SlugField(help_text='Stable public identifier used by the catalog API.', max_length=100, unique=True)),
                ('service_type', models.CharField(choices=[('ogc_api_features', 'OGC API Features'), ('sensorthings', 'OGC SensorThings API')], help_text='Supported service type. New types need dedicated frontend support.', max_length=32)),
                ('base_url', models.URLField(help_text='OGC API: landing page or multi-API catalog root. SensorThings: service root, with or without the /v1.x version segment.', max_length=500)),
                ('mqtt_url', models.CharField(blank=True, help_text='SensorThings only: MQTT-over-WebSocket endpoint (wss://…) for live values.', max_length=500)),
                ('title', models.CharField(help_text='Title shown to users', max_length=200)),
                ('attribution', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private (signed-in users only)')], db_index=True, default='PRIVATE', help_text='PUBLIC: listed to everyone. PRIVATE: not listed to anonymous users, listed to signed-in users. This controls what TOSCA lists; the remote data itself stays publicly reachable.', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('show_uncurated', models.BooleanField(default=False, help_text="Also offer the service's full dataset/layer list besides curated categories.")),
                ('allow_full_load', models.BooleanField(default=True, help_text="OGC API: allow 'Load all' (downloading every matching feature).")),
                ('allow_live_updates', models.BooleanField(default=True, help_text='SensorThings: allow live MQTT updates (requires an MQTT URL).')),
                ('allow_server_filters', models.BooleanField(default=True, help_text='OGC API: allow attribute selection and server-side filters.')),
                ('max_features', models.PositiveIntegerField(blank=True, help_text='Optional upper bound of features per layer load. Empty = app default.', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='Owning organization; scopes who may manage this service.', on_delete=django.db.models.deletion.PROTECT, related_name='external_services', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'External Service',
                'verbose_name_plural': 'External Services',
                'ordering': ['title', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CategoryItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower values are listed first.')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('ogc_dataset_id', models.CharField(blank=True, help_text='OGC API only: dataset (API) id inside a multi-API catalog; empty for a single landing page.', max_length=200)),
                ('ogc_collection_ids', models.JSONField(blank=True, default=list, help_text='OGC API only: collection ids; several ids are rendered as one merged layer.')),
                ('default_properties', models.JSONField(blank=True, default=list, help_text='OGC API only: attributes requested by default (empty = all).')),
                ('default_filter', models.JSONField(blank=True, default=list, help_text='OGC API only: initial filter conditions, a list of {"property", "operator", "value"} (operators: eq, neq, lt, lte, gt, gte, contains).')),
                ('sta_service_name', models.CharField(blank=True, help_text='SensorThings only: Datastream properties.serviceName.', max_length=200)),
                ('sta_layer_name', models.CharField(blank=True, help_text='SensorThings only: Datastream properties.layerName.', max_length=200)),
                ('color', models.CharField(default='#0288d1', help_text='Default map color.', max_length=7, validators=[django.core.validators.RegexValidator(message='Use a 6-digit hex color such as #0288d1.', regex='^#[0-9a-fA-F]{6}$')])),
                ('min_zoom', models.DecimalField(blank=True, decimal_places=1, help_text='Load features only from this zoom level. Empty = always.', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('24'))])),
                ('availability_state', models.CharField(choices=[('UNKNOWN', 'Not checked yet'), ('OK', 'Available'), ('MISSING', 'Missing at the service'), ('ERROR', 'Check failed')], default='UNKNOWN', editable=False, max_length=20)),
                ('feature_count', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_check_error', models.TextField(blank=True, editable=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='external_catalog.category')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='external_catalog.externalservice')),
            ],
            options={
                'verbose_name': 'External Category Item',
                'verbose_name_plural': 'External Category Items',
                'ordering': ['display_order', 'title', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active', 'visibility'], name='external_ca_is_acti_ee69c5_idx'),
        ),
        migrations.AddIndex(
            model_name='externalservice',
            index=models.Index(fields=['is_active', 'visibility'], name='external_ca_is_acti_c13a6b_idx'),
        ),
    ]
