# Generated by Django 5.2.16 on 2026-10-07 08:28

import uuid

from django.db import migrations, models


def split_collections(apps, schema_editor):
    """One collection per item: keep the first on the item, copy the item
    for every further collection (merged layers are no longer supported).
    The old field is dropped in 0004: Postgres cannot alter a table in the
    transaction that just inserted rows with deferred FK checks."""
    CategoryItem = apps.get_model("external_catalog", "CategoryItem")
    for item in CategoryItem.objects.exclude(ogc_collection_ids=[]):
        first, *rest = item.ogc_collection_ids
        CategoryItem.objects.filter(pk=item.pk).update(ogc_collection_id=first)
        for offset, collection_id in enumerate(rest, start=1):
            item.pk = uuid.uuid7()
            item.ogc_collection_id = collection_id
            item.display_order += offset
            item.title = f"{item.title} ({collection_id})"[:200]
            item._state.adding = True
            item.save()


def join_collections(apps, schema_editor):
    CategoryItem = apps.get_model("external_catalog", "CategoryItem")
    for item in CategoryItem.objects.exclude(ogc_collection_id=""):
        CategoryItem.objects.filter(pk=item.pk).update(ogc_collection_ids=[item.ogc_collection_id])


class Migration(migrations.Migration):

    dependencies = [
        ('external_catalog', '0002_seed_external_catalog_entitlements'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryitem',
            name='ogc_collection_id',
            field=models.CharField(blank=True, help_text='OGC API only: the collection shown by this item.', max_length=200),
        ),
        migrations.RunPython(split_collections, join_collections),
    ]
