# Generated by Django 5.2.16 on 2026-10-07 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_catalog', '0004_remove_categoryitem_ogc_collection_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryitem',
            name='dataset_title',
            field=models.CharField(blank=True, help_text='OGC dataset title or SensorThings serviceName.', max_length=500),
        ),
        migrations.AddField(
            model_name='externalservice',
            name='catalog_load_error',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='externalservice',
            name='catalog_load_note',
            field=models.TextField(blank=True, editable=False, help_text='Problems of the last load that did not stop it.'),
        ),
        migrations.AddField(
            model_name='externalservice',
            name='catalog_load_started_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='externalservice',
            name='catalog_loaded_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.CreateModel(
            name='ServiceSource',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dataset_id', models.CharField(blank=True, max_length=200)),
                ('dataset_title', models.CharField(blank=True, max_length=500)),
                ('source_id', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('item_type', models.CharField(blank=True, max_length=50)),
                ('geojson', models.BooleanField(default=True, help_text='OGC: offers GeoJSON items (can be shown on the map).')),
                ('count', models.PositiveIntegerField(blank=True, help_text='Features (OGC) or datastreams (STA).', null=True)),
                ('themes', models.JSONField(blank=True, default=list, help_text='EU data theme codes, e.g. TRAN.')),
                ('harvested_at', models.DateTimeField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='external_catalog.externalservice')),
            ],
            options={
                'verbose_name': 'Indexed source',
                'ordering': ['dataset_title', 'title', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='servicesource',
            constraint=models.UniqueConstraint(fields=('service', 'dataset_id', 'source_id'), name='external_catalog_unique_service_source'),
        ),
    ]
