# Generated by Django 5.1.14 on 2026-03-03 12:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('formbuilder', '0003_formfield_question_alter_formfield_label'),
        ('geocontext', '0001_initial'),
        ('layerrefs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackLayer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layerrefs.layerref')),
            ],
            options={
                'verbose_name': 'Feedback Layer',
                'verbose_name_plural': 'Feedback Layers',
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeoFeedback',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('rating_enabled', models.BooleanField(default=True, help_text='Enable star rating collection.')),
                ('form_enabled', models.BooleanField(default=False, help_text='Enable custom form submission.')),
                ('allow_drawings', models.BooleanField(default=False, help_text='Allow users to submit spatial drawings.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed')], db_index=True, default='draft', max_length=20)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=20)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='campaigns.campaign')),
                ('context', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to='geocontext.geocontext')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_feedbacks', to=settings.AUTH_USER_MODEL)),
                ('custom_form', models.ForeignKey(blank=True, help_text='Link to a form created with django-basic-form-builder.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='formbuilder.customform')),
                ('layers', models.ManyToManyField(blank=True, related_name='feedbacks', through='feedback.FeedbackLayer', to='layerrefs.layerref')),
            ],
            options={
                'verbose_name': 'GeoFeedback',
                'verbose_name_plural': 'GeoFeedbacks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='feedbacklayer',
            name='feedback',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.geofeedback'),
        ),
        migrations.AddIndex(
            model_name='geofeedback',
            index=models.Index(fields=['campaign'], name='feedback_ge_campaig_58e14b_idx'),
        ),
        migrations.AddIndex(
            model_name='geofeedback',
            index=models.Index(fields=['status'], name='feedback_ge_status_b17592_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='feedbacklayer',
            unique_together={('feedback', 'layer')},
        ),
    ]
