# Generated by Django 5.1.14 on 2026-03-03 12:34

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackSubmission',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='Star rating from 1 to 5.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('form_data', models.JSONField(blank=True, default=None, help_text='Dynamic form answers stored as JSON (from formbuilder).', null=True)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(blank=True, help_text='Spatial drawing (Point, LineString, or Polygon).', null=True, srid=4326)),
                ('is_anonymized', models.BooleanField(default=False, help_text='Whether personally identifiable information has been removed.')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='feedback.geofeedback')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feedback Submission',
                'verbose_name_plural': 'Feedback Submissions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['feedback'], name='feedback_fe_feedbac_e5e01e_idx'), models.Index(fields=['submitted_by'], name='feedback_fe_submitt_cff0e0_idx')],
            },
        ),
    ]
