# Generated by Django 5.1.15 on 2026-04-28 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedbacksubmission'),
        ('geodata_providers', '0003_layer_opaque_layer_queryable_and_more'),
    ]

    operations = [
        # Destructive: drop existing through-rows that point at the retired
        # layerrefs.LayerRef table before re-targeting the FK at
        # geodata_providers.Layer. Pre-production, no row preservation needed.
        migrations.RunSQL(
            sql="TRUNCATE TABLE feedback_feedbacklayer;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='feedbacklayer',
            name='layer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_uses', to='geodata_providers.layer'),
        ),
        migrations.AlterField(
            model_name='geofeedback',
            name='layers',
            field=models.ManyToManyField(blank=True, related_name='feedbacks', through='feedback.FeedbackLayer', to='geodata_providers.layer'),
        ),
    ]
