# Generated by Django 5.2.16 on 2026-07-10 08:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_alter_campaign_id'),
        ('feedback', '0004_alter_feedbacklayer_id_alter_feedbacksubmission_id_and_more'),
        ('formbuilder', '0003_formfield_question_alter_formfield_label'),
        ('geocontext', '0004_alter_geocontext_id'),
        ('geodata_providers', '0007_alter_geodataengine_is_active_alter_layer_sync_state_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='geofeedback',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed')], default='draft', max_length=20),
        ),
        migrations.AddIndex(
            model_name='geofeedback',
            index=models.Index(fields=['status', 'visibility'], name='feedback_geofb_stat_vis_idx'),
        ),
    ]
