# Generated by Django 5.2.16 on 2026-07-13 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_alter_geofeedback_status_and_more'),
        ('geodata_providers', '0008_alter_layer_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feedbacklayer',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='feedbacklayer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name='feedbacklayer',
            constraint=models.UniqueConstraint(fields=('feedback', 'layer'), name='feedback_feedbacklayer_uniq'),
        ),
    ]
