# Generated by Django 5.1.14 on 2026-02-04 13:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('geocontext', '0001_initial'),
        ('layerrefs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoStory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='geostories', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geostories', to='campaigns.campaign')),
                ('context', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geostory', to='geocontext.geocontext')),
            ],
            options={
                'verbose_name': 'GeoStory',
                'verbose_name_plural': 'GeoStories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeoStoryLayer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('geostory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geostories.geostory')),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layerrefs.layerref')),
            ],
            options={
                'verbose_name': 'GeoStory Layer',
                'verbose_name_plural': 'GeoStory Layers',
                'ordering': ['display_order', 'created_at'],
                'unique_together': {('geostory', 'layer')},
            },
        ),
        migrations.AddField(
            model_name='geostory',
            name='layers',
            field=models.ManyToManyField(blank=True, related_name='geostories', through='geostories.GeoStoryLayer', to='layerrefs.layerref'),
        ),
    ]
