# Generated by Django 5.1.15 on 2026-04-28 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata_providers', '0003_layer_opaque_layer_queryable_and_more'),
        ('geostories', '0001_initial'),
    ]

    operations = [
        # Destructive: drop existing through-rows that point at the retired
        # layerrefs.LayerRef table before re-targeting the FK at
        # geodata_providers.Layer. Pre-production, no row preservation needed.
        migrations.RunSQL(
            sql="TRUNCATE TABLE geostories_geostorylayer;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='geostory',
            name='layers',
            field=models.ManyToManyField(blank=True, related_name='geostories', through='geostories.GeoStoryLayer', to='geodata_providers.layer'),
        ),
        migrations.AlterField(
            model_name='geostorylayer',
            name='layer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geostory_uses', to='geodata_providers.layer'),
        ),
    ]
