# Generated by Django 5.1.15 on 2026-04-29

import tosca_api.apps.geostories.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geostories", "0002_alter_geostory_layers_alter_geostorylayer_layer"),
    ]

    operations = [
        migrations.AddField(
            model_name="geostory",
            name="hero_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=tosca_api.apps.geostories.models.geostory_hero_image_upload_to,
            ),
        ),
        migrations.AddField(
            model_name="geostory",
            name="hero_image_alt",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
