# Generated by Django 5.2.16 on 2026-07-10 08:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geostories', '0003_geostory_hero_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geostory',
            name='id',
            field=models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='geostorylayer',
            name='id',
            field=models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False),
        ),
    ]
