# Generated by Django 5.2.16 on 2026-07-13 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata_providers', '0008_alter_layer_unique_together_and_more'),
        ('geostories', '0004_alter_geostory_id_alter_geostorylayer_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='geostorylayer',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='geostorylayer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name='geostorylayer',
            constraint=models.UniqueConstraint(fields=('geostory', 'layer'), name='geostories_geostorylayer_uniq'),
        ),
    ]
