# Generated by Django 5.2.16 on 2026-08-14 12:37

import tosca_api.apps.geostories.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geostories', '0005_alter_geostorylayer_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='geostory',
            name='hero_image_storage_alias',
            field=models.CharField(choices=[('default', 'Private (default)'), ('media_public', 'Public'), ('media_archive', 'Archive')], default='default', help_text='Storage alias currently holding hero_image; maintained by the media lifecycle.', max_length=20),
        ),
        migrations.AlterField(
            model_name='geostory',
            name='hero_image',
            field=tosca_api.apps.geostories.models.HeroImageField(blank=True, null=True, upload_to=tosca_api.apps.geostories.models.geostory_hero_image_upload_to),
        ),
    ]
