# Generated by Django 5.2.16 on 2026-10-07 14:02

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata_providers', '0017_geodataengine_organizations'),
        ('geostories', '0010_geostory_about_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoStoryScene',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=255)),
                ('caption', models.TextField(blank=True, default='')),
                ('center_lng', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('center_lat', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('zoom', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)])),
                ('bearing', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('pitch', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(85)])),
                ('bounds', models.JSONField(blank=True, help_text='Captured viewport as [west, south, east, north] in EPSG:4326.', null=True)),
                ('transition', models.CharField(choices=[('fly', 'Fly'), ('ease', 'Ease'), ('jump', 'Jump')], default='fly', max_length=10)),
                ('duration_ms', models.PositiveIntegerField(default=1500, validators=[django.core.validators.MaxValueValidator(10000)])),
                ('geostory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='geostories.geostory')),
            ],
            options={
                'verbose_name': 'GeoStory Scene',
                'verbose_name_plural': 'GeoStory Scenes',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeoStorySceneLayer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('source_kind', models.CharField(choices=[('catalog_layer', 'Catalog layer')], default='catalog_layer', max_length=30)),
                ('render_layer_ids', models.JSONField(blank=True, default=list, help_text="Optional MBStyle layer IDs for this scene. Leave empty to use the pinned assignment's selected layer IDs.")),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('opacity', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('feature_mode', models.CharField(choices=[('all', 'All features'), ('only', 'Only selected features'), ('highlight', 'Highlight selected features')], default='all', max_length=20)),
                ('feature_id_attribute', models.CharField(blank=True, default='', max_length=255)),
                ('feature_ids', models.JSONField(blank=True, default=list, help_text='Values of the feature ID attribute to show or highlight.')),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geostory_scene_uses', to='geodata_providers.layer')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scene_layers', to='geostories.geostoryscene')),
                ('style_assignment', models.ForeignKey(blank=True, help_text="Pinned style assignment; defaults to the layer's active default assignment.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='geostory_scene_uses', to='geodata_providers.layerstyleassignment')),
            ],
            options={
                'verbose_name': 'GeoStory Scene Layer',
                'verbose_name_plural': 'GeoStory Scene Layers',
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='geostoryscene',
            constraint=models.UniqueConstraint(fields=('geostory', 'order'), name='geostories_scene_unique_order'),
        ),
        migrations.AddConstraint(
            model_name='geostoryscenelayer',
            constraint=models.UniqueConstraint(fields=('scene', 'layer', 'style_assignment'), name='geostories_scenelayer_unique_layer_style'),
        ),
    ]
