# Generated by Django 5.2.16 on 2026-10-07 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata_providers', '0017_geodataengine_organizations'),
        ('geostories', '0012_scenes_replace_story_layers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geostorylayer',
            name='style_assignment',
            field=models.ForeignKey(blank=True, help_text="Pinned style assignment; defaults to the layer's active default assignment.", null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='geostory_uses', to='geodata_providers.layerstyleassignment'),
        ),
        migrations.AlterField(
            model_name='geostoryscenelayer',
            name='style_assignment',
            field=models.ForeignKey(blank=True, help_text="Pinned style assignment; defaults to the layer's active default assignment.", null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='geostory_scene_uses', to='geodata_providers.layerstyleassignment'),
        ),
    ]
