# Generated by Django 5.2.16 on 2026-08-12 11:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='Derives Keycloak role names: ROLE_<SLUG>_READER/WRITER/ADMIN. Stable identifier -- renaming means renaming Keycloak roles + GeoServer ACL too.', unique=True)),
                ('keycloak_org_id', models.CharField(blank=True, help_text='Native Keycloak organization id. Nullable until reconciled.', max_length=255, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'ordering': ['name'],
            },
        ),
    ]
