# Generated by Django 5.2.16 on 2026-08-13 09:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_seed_dcs_and_backfill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='slug',
            field=models.SlugField(help_text='Single segment (no underscore). Derives Keycloak role names: ROLE_<SLUG>_READER/WRITER/ADMIN. Stable identifier -- renaming means renaming Keycloak roles + GeoServer ACL too.', unique=True, validators=[django.core.validators.RegexValidator(message='Slug must be a single segment: lowercase letters, digits and hyphens only (no underscore -- it delimits role-name segments).', regex='^[a-z0-9-]+$')]),
        ),
    ]
