# Generated by Django 5.2.16 on 2026-08-19 10:35

import django.db.models.deletion
import tosca_api.apps.organizations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_organization_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationAppEntitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_label', models.CharField(max_length=100, validators=[tosca_api.apps.organizations.models.validate_entitleable_app_label])),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_entitlements', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Organization App Entitlement',
                'verbose_name_plural': 'Organization App Entitlements',
                'unique_together': {('organization', 'app_label')},
            },
        ),
    ]
