# Generated by Django 5.2.16 on 2026-08-19 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_seed_all_entitlements'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAuthorizationSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org_roles', models.JSONField(blank=True, default=dict, help_text="Org slug -> role level captured from the last successful browser login, e.g. {'dcs': 'ADMIN', 'qg2': 'WRITER'}.")),
                ('default_org', models.CharField(blank=True, default='', help_text='Org slug the PoC actually authorizes against (org_roles[default_org]). Empty until a login has synced one.', max_length=255)),
                ('synced_at', models.DateTimeField(help_text='When these claims were pulled from the token -- distinct from `updated_at`, which only tracks row writes.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='authorization_snapshot', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Authorization Snapshot',
                'verbose_name_plural': 'User Authorization Snapshots',
            },
        ),
    ]
