# Generated by Django 5.2.16 on 2026-08-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_userauthorizationsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauthorizationsnapshot',
            name='platform_exempt',
            field=models.BooleanField(default=False, help_text="Whether the last login's roles included DJANGO_STAFF/DJANGO_SUPERADMIN (canonical §2b platform exemption from org scoping). Captured explicitly -- not inferred from user.is_staff/is_superuser, which can be toggled independently of Keycloak via the admin's own UserAdmin (security tickets ticket 07)."),
        ),
    ]
