# Generated by Django 5.1.14 on 2026-02-05 10:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureLink',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('link_type', models.CharField(choices=[('direct', 'Direct Link'), ('read_more', 'Read More'), ('action', 'Action')], default='direct', max_length=20)),
                ('source_object_id', models.UUIDField()),
                ('target_object_id', models.UUIDField()),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_links', to='campaigns.campaign')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feature_links', to=settings.AUTH_USER_MODEL)),
                ('source_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_link_sources', to='contenttypes.contenttype')),
                ('target_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_link_targets', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Feature Link',
                'verbose_name_plural': 'Feature Links',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source_content_type', 'source_object_id'], name='featurelink_source__70db25_idx'), models.Index(fields=['target_content_type', 'target_object_id'], name='featurelink_target__a6b0f2_idx')],
                'constraints': [models.UniqueConstraint(fields=('source_content_type', 'source_object_id', 'target_content_type', 'target_object_id'), name='unique_feature_link')],
            },
        ),
    ]
