# Generated by Django 5.2.16 on 2026-07-10 08:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('featurelinks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurelink',
            name='id',
            field=models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False),
        ),
    ]
