# Generated by Django 5.2 on 2026-08-14.

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("storage_path", models.CharField(max_length=1024, unique=True)),
                ("original_name", models.CharField(blank=True, max_length=255)),
                ("mime", models.CharField(max_length=100)),
                ("width", models.PositiveIntegerField()),
                ("height", models.PositiveIntegerField()),
                ("size", models.PositiveBigIntegerField()),
                (
                    "uploader",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="media_assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["created_at"], name="core_mediaa_created_56c4bc_idx"),
                    models.Index(fields=["mime"], name="core_mediaa_mime_a51381_idx"),
                ],
            },
        ),
    ]
