# Generated by Django 5.2.16 on 2026-08-14 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_campaign_organization_nonnull'),
        ('core', '0001_mediaasset'),
        ('organizations', '0003_alter_organization_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='campaign',
            field=models.ForeignKey(blank=True, help_text='Campaign this asset is used in, when known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_assets', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='owner_org',
            field=models.ForeignKey(blank=True, help_text='Owning organization, derived from the campaign this asset is used in (nullable: orphan/unlinked uploads have no owner).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_assets', to='organizations.organization'),
        ),
        migrations.AddIndex(
            model_name='mediaasset',
            index=models.Index(fields=['owner_org'], name='core_mediaa_owner_o_39410e_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaasset',
            index=models.Index(fields=['campaign'], name='core_mediaa_campaig_85370e_idx'),
        ),
    ]
