# Generated by Django 5.2.16 on 2026-08-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_backfill_media_asset_ownership'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='storage_alias',
            field=models.CharField(choices=[('default', 'Private (default)'), ('media_public', 'Public'), ('media_archive', 'Archive')], default='default', help_text='Which storage alias (bucket) currently holds this object. Updated by core.media_lifecycle when a Campaign/GeoStory archive/restore transition moves the object between buckets.', max_length=20),
        ),
    ]
