# Generated by Django 5.2.16 on 2026-08-12 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_alter_campaign_id'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Owning organization.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='organizations.organization'),
        ),
    ]
